### ISSUE TITLE
Option to disable auto-centering?

### ISSUE THREAD

**Issue by swiftSwathSee** [raptorswing/MouseToJoystick#13]
Needs an option to disable the auto-centering so that it can be used as a true joystick instead of just an arcade joystick.

**Comment by ahmad244** [comment]
been trying to do that for quite sometime I tried to compile the code myself but with no avail, i always get a ton of error messages, like ((cannot open source file "QApplication"	MouseToJoystick	)) if only I can compile the code I can then just (maybe) get the mouse centering to stop by commenting out line 126 of the MainWindow.h file that is 
//QCursor::setPos(screenCenter);
so that the centering can stop or maybe make the centering of the mouse a gradual thing not an instantaneous thing, if you get what I mean, aghh

**Comment by raptorswing** [comment]
Hello!

After about six years I've finally taken some time to briefly revisit this project.

The result is a rewrite in C#, found [here](https://github.com/raptorswing/MouseToJoystick/releases/tag/2.0-beta). It includes an option to disable the "auto-centering". Please give it a try and I hope it makes things easier for you.

**Comment by swiftSwathSee** [comment]
Works great. I've only used it in one program, but it hasn't had any issues after 25 hours of testing. Maybe a future version could remember the options.

**Comment by raptorswing** [comment]
Glad that it's working for you.

I agree that remembering the options would be a helpful improvement... filed #16 to track.
