### ISSUE TITLE
Cannot compile the source.

### ISSUE THREAD

**Issue by Osjur** [raptorswing/MouseToJoystick#2]
Hi, I've been trying to compile this with QT Creator without any luck. I get undefined reference errors which point out to if (!vJoyEnabled()) etc. 

Some tips on how to actually compile this would be nice.

**Comment by raptorswing** [comment]
vJoyEnabled() is defined in [this file.](https://github.com/raptorswing/MouseToJoystick/blob/master/vjoyInc/vjoyinterface.h), part of the [vJoy project](http://vjoystick.sourceforge.net/site/).

I haven't played with this project in over a year so there is a possibility that there is some weirdness due to a newer version of Qt or maybe I just included something wrong.

If I were you I'd double-check that vjoyinterface.h is being included properly. Then I would double check that the vjoy static library in vjoyLib is being linked against properly. If you are on a 32-bit OS/platform you may need to change the .pro file to target the 32-bit vjoy library instead of the default 64-bit version.

**Comment by Osjur** [comment]
Thanks for the input, I was able to compile the 32bit version with my own modifications to axis handling. I guess you manually compiled the x64 QT Creator because the standard only comes with 32bit mingw compiler?

**Comment by raptorswing** [comment]
It's been a while since I wrote this, but I think I defaulted the linking to the 64-bit version because I was running on a 64-bit machine. I should improve the makefile to detect which one to link automatically.
