### ISSUE TITLE
trying to play Tie Fighter

### ISSUE THREAD

**Issue by viktriiceberg** [raptorswing/MouseToJoystick#3]
I'm trying to play Tie Fighter with this script but when I start the script my craft spins to the up and right direction - any way that I can fix this?

**Comment by raptorswing** [comment]
Did you follow the instructions in the readme? Are you running on a single- or multi-monitor machine?

**Comment by viktriiceberg** [comment]
I'm running on a single monitor machine. I did follow the readme and I can pilot the craft and shoot lasers. The problem is that if I centre my mouse and don't move, my craft moves itself. I can move in another direction to compensate so I know the script does work (I also can shoot lasers which is something I can't do without the script).

**Comment by raptorswing** [comment]
Ok - I seem to remember seeing this happen occasionally. Not 100% sure on the cause - what is your screen resolution when you're in-game?

One solution may be to add a "dead spot" to the code so that mouse movements below a certain threshold are ignored. I experimented with this long ago and found I didn't like it because it made it difficult to do very fine course corrections while flying.

**Comment by kempeitai** [comment]
I have found that this behavior occurs if tie95.exe is located in long path.
Placing it closer to the root directory eliminates the problem.

**Comment by raptorswing** [comment]
That's bizarre and interesting. Glad you were able to make it work.
